/* Based on the header generated by cbindgen for codetracer_trace_writer_ffi.
 * Modified: prefixed conflicting enum values to avoid C name collisions.
 * FfiEventLogKind.ERROR -> EVT_ERROR
 * FfiTypeKind.ERROR -> TK_ERROR
 */

#ifndef CODETRACER_TRACE_WRITER_H
#define CODETRACER_TRACE_WRITER_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Event-log kind -- mirrors EventLogKind.
 */
typedef enum FfiEventLogKind {
    EVT_WRITE = 0,
    EVT_WRITE_FILE = 1,
    EVT_WRITE_OTHER = 2,
    EVT_READ = 3,
    EVT_READ_FILE = 4,
    EVT_READ_OTHER = 5,
    EVT_READ_DIR = 6,
    EVT_OPEN_DIR = 7,
    EVT_CLOSE_DIR = 8,
    EVT_SOCKET = 9,
    EVT_OPEN = 10,
    EVT_ERROR = 11,
    EVT_TRACE_LOG_EVENT = 12,
    EVT_EVM_EVENT = 13,
} FfiEventLogKind;

/**
 * Trace file format -- mirrors TraceEventsFileFormat.
 */
typedef enum FfiTraceFormat {
    FMT_JSON = 0,
    FMT_BINARY_V0 = 1,
    FMT_BINARY = 2,
} FfiTraceFormat;

/**
 * Type kind -- mirrors TypeKind (subset used by the FFI).
 */
typedef enum FfiTypeKind {
    TK_SEQ = 0,
    TK_SET = 1,
    TK_HASH_SET = 2,
    TK_ORDERED_SET = 3,
    TK_ARRAY = 4,
    TK_VARARGS = 5,
    TK_STRUCT = 6,
    TK_INT = 7,
    TK_FLOAT = 8,
    TK_STRING = 9,
    TK_C_STRING = 10,
    TK_CHAR = 11,
    TK_BOOL = 12,
    TK_LITERAL = 13,
    TK_REF = 14,
    TK_RECURSION = 15,
    TK_RAW = 16,
    TK_ENUM = 17,
    TK_ENUM16 = 18,
    TK_ENUM32 = 19,
    TK_C = 20,
    TK_TABLE_KIND = 21,
    TK_UNION = 22,
    TK_POINTER = 23,
    TK_ERROR = 24,
    TK_FUNCTION_KIND = 25,
    TK_TYPE_VALUE = 26,
    TK_TUPLE = 27,
    TK_VARIANT = 28,
    TK_HTML = 29,
    TK_NONE = 30,
    TK_NON_EXPANDED = 31,
    TK_ANY = 32,
    TK_SLICE = 33,
} FfiTypeKind;

/**
 * Opaque handle passed across the FFI boundary.
 */
typedef struct TraceWriterHandle TraceWriterHandle;

/**
 * Retrieve the last error message for the current thread.
 *
 * Returns a pointer to a NUL-terminated UTF-8 string.  The pointer is valid
 * until the next FFI call **on the same thread**.  Returns an empty string
 * when no error has occurred.
 */
const char *trace_writer_last_error(void);

/**
 * Create a new trace writer.
 *
 * `program` is a NUL-terminated C string identifying the program being
 * traced.  `format` selects the on-disk serialisation format.
 *
 * Returns a heap-allocated handle that **must** be freed with
 * trace_writer_free.  Returns NULL on failure (check
 * trace_writer_last_error).
 */
struct TraceWriterHandle *trace_writer_new(const char *program, enum FfiTraceFormat format);

/**
 * Free a trace writer handle.  Passing NULL is a no-op.
 */
void trace_writer_free(struct TraceWriterHandle *handle);

bool trace_writer_begin_metadata(struct TraceWriterHandle *handle, const char *path);

bool trace_writer_finish_metadata(struct TraceWriterHandle *handle);

bool trace_writer_begin_events(struct TraceWriterHandle *handle, const char *path);

bool trace_writer_finish_events(struct TraceWriterHandle *handle);

bool trace_writer_begin_paths(struct TraceWriterHandle *handle, const char *path);

bool trace_writer_finish_paths(struct TraceWriterHandle *handle);

void trace_writer_start(struct TraceWriterHandle *handle, const char *path, int64_t line);

/**
 * Override the working directory recorded in the trace metadata.
 *
 * By default the workdir is set to the process's current directory at
 * the time trace_writer_new is called.  Call this before
 * trace_writer_finish_metadata to record a different directory.
 */
void trace_writer_set_workdir(struct TraceWriterHandle *handle, const char *workdir);

void trace_writer_register_step(struct TraceWriterHandle *handle, const char *path, int64_t line);

/**
 * Register a function and return its ID.  Returns usize::MAX on error.
 */
uintptr_t trace_writer_ensure_function_id(struct TraceWriterHandle *handle,
                                          const char *name,
                                          const char *path,
                                          int64_t line);

/**
 * Register a type and return its ID.  Returns usize::MAX on error.
 */
uintptr_t trace_writer_ensure_type_id(struct TraceWriterHandle *handle,
                                      enum FfiTypeKind kind,
                                      const char *lang_type);

/**
 * Register a call to the function identified by function_id.
 *
 * For simplicity the FFI does not expose argument passing -- call
 * trace_writer_register_variable_with_full_value for each arg before
 * this function.
 */
void trace_writer_register_call(struct TraceWriterHandle *handle, uintptr_t function_id);

/**
 * Register a function return with no explicit return value.
 */
void trace_writer_register_return(struct TraceWriterHandle *handle);

/**
 * Register a function return with an integer return value.
 */
void trace_writer_register_return_int(struct TraceWriterHandle *handle,
                                      int64_t value,
                                      enum FfiTypeKind type_kind,
                                      const char *type_name);

/**
 * Register a function return with a string (raw) return value.
 */
void trace_writer_register_return_raw(struct TraceWriterHandle *handle,
                                      const char *value_repr,
                                      enum FfiTypeKind type_kind,
                                      const char *type_name);

/**
 * Register a variable with an integer value.
 */
void trace_writer_register_variable_int(struct TraceWriterHandle *handle,
                                        const char *name,
                                        int64_t value,
                                        enum FfiTypeKind type_kind,
                                        const char *type_name);

/**
 * Register a variable with a string (raw) value representation.
 */
void trace_writer_register_variable_raw(struct TraceWriterHandle *handle,
                                        const char *name,
                                        const char *value_repr,
                                        enum FfiTypeKind type_kind,
                                        const char *type_name);

/**
 * Register an I/O or special event with optional metadata.
 *
 * `metadata` is an arbitrary NUL-terminated string attached to the event
 * (for example a file descriptor or channel name).  Pass NULL or an empty
 * string when no metadata is needed.
 */
void trace_writer_register_special_event(struct TraceWriterHandle *handle,
                                         enum FfiEventLogKind kind,
                                         const char *metadata,
                                         const char *content);

#endif  /* CODETRACER_TRACE_WRITER_H */
