# Nix derivation for codetracer-wasm-recorder.
#
# Generated by codetracer-launcher/packaging/recorder-templates/generate.py
# from codetracer-wasm-recorder/packaging/recorder-metadata.yml.
# DO NOT edit this file by hand — re-run the generator instead.
#
# Per CodeTracer Launcher §11 (M11), this is a *recorder-only*
# derivation. The `ct` launcher itself ships via the M9
# packaging/nix/default.nix in the codetracer-launcher repo.
#
# Usage:
#
#   nix-build packaging/nix/default.nix
#   ./result/bin/codetracer-wasm-recorder --version
#
# Or as a flake-output (the per-recorder flake.nix should pass
# `srcOverride = ./.` and `version = ...`):
#
#   inputs.codetracer-wasm-recorder.url = "github:metacraft-labs/codetracer-wasm-recorder";
#   environment.systemPackages = [
#     inputs.codetracer-wasm-recorder.packages.${system}.default
#   ];

{
  lib ? (import <nixpkgs> { }).lib,
  rustPlatform ? (import <nixpkgs> { }).rustPlatform,
  stdenv ? (import <nixpkgs> { }).stdenv,
  fetchFromGitHub ? (import <nixpkgs> { }).fetchFromGitHub,
  # When `srcOverride` is set the build uses the supplied source tree;
  # otherwise it fetches from the public repo at the pinned tag.
  # Source-tree override is the path Nix-based CI takes (it already
  # has the checkout).
  srcOverride ? null,
  version ? "0.1.0",
}:

rustPlatform.buildRustPackage rec {
  pname = "codetracer-wasm-recorder";
  inherit version;

  src =
    if srcOverride != null then
      srcOverride
    else
      fetchFromGitHub {
        owner = "metacraft-labs";
        repo = "codetracer-wasm-recorder";
        rev = "v${version}";
        # The publish workflow rewrites this placeholder before
        # tagging. When building locally pass `srcOverride = ./.;`.
        sha256 = lib.fakeSha256;
      };

  # Cargo.lock pins every dep — `cargoLock.lockFile` keeps the build
  # reproducible without requiring `outputHashes` for every git dep.
  cargoLock = {
    lockFile = src + "/Cargo.lock";
    # Most blockchain recorders use git deps for tree-sitter grammars
    # or in-development library forks; allow building with a hash
    # override per dep if/when the recorder adds one.
    allowBuiltinFetchGit = true;
  };

  # Some recorders depend on the codetracer trace-format Nim
  # library, which is built and linked at the Cargo level. The
  # generator emits a `buildInputs` list below sourced from the
  # recorder's metadata so the right system libs are present.
  buildInputs = [ ];

  doCheck = false; # `cargo test` runs in the recorder's own CI

  meta = with lib; {
    description = "CodeTracer recorder for WebAssembly modules (wazero engine)";
    homepage = "https://github.com/metacraft-labs/codetracer-wasm-recorder";
    license = licenses.asl20;
    platforms = platforms.unix;
    mainProgram = "codetracer-wasm-recorder";
  };
}
